"""init tryon + biz tables

Revision ID: 20608557862f
Revises: 
Create Date: 2025-10-21 16:14:19.922563

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

import sqlmodel

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '20608557862f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_library',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('sex', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('tags', mysql.JSON(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tryon_example',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category_leaf_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tryon_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tryon_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('clothing_set', mysql.JSON(), nullable=True),
    sa.Column('category_leaf_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('aspect_ratio', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('fitting_style', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('is_oversize', sa.Boolean(), nullable=False),
    sa.Column('params', mysql.JSON(), nullable=True),
    sa.Column('meta', mysql.JSON(), nullable=True),
    sa.Column('image_urls', mysql.JSON(), nullable=True),
    sa.Column('inference_time', sa.Float(), nullable=True),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['tryon_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ai_clothes_project')
    op.drop_table('ai_bag')
    op.drop_index('index1', table_name='hot_pikpop')
    op.drop_table('hot_pikpop')
    op.drop_index('uk_deleted_public_id', table_name='deleted_public_ids_log')
    op.drop_table('deleted_public_ids_log')
    op.drop_index('index1', table_name='hot_tk')
    op.drop_table('hot_tk')
    op.drop_table('hot_cate')
    op.drop_table('biz_customer_category')
    op.drop_table('file_detail')
    op.drop_table('ai_clothes_model')
    op.drop_table('ai_clothes_detail')
    op.drop_table('biz_invite_score')
    op.drop_table('ai_bag_detail')
    op.drop_table('ai_bag_type')
    op.drop_table('biz_customer_order')
    op.drop_table('ai_bag_project')
    op.drop_index('index1', table_name='hot_amazon')
    op.drop_table('hot_amazon')
    op.drop_table('ai_clothes')
    op.drop_table('file_part_detail')
    op.drop_table('ai_clothes_model_set')
    op.drop_table('ai_clothes_example')
    op.add_column('biz_customer', sa.Column('my_invitation_co', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True))
    op.alter_column('biz_customer', 'id',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=32),
               comment=None,
               existing_comment='主键id',
               existing_nullable=False)
    op.alter_column('biz_customer', 'email',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100),
               comment=None,
               existing_comment='email',
               existing_nullable=True)
    op.alter_column('biz_customer', 'register_type',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=10),
               comment=None,
               existing_comment='0-账号密码登录，1-gmail登录',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('biz_customer', 'role',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100),
               comment=None,
               existing_comment='注册时填写的factory',
               existing_nullable=True)
    op.alter_column('biz_customer', 'category',
               existing_type=mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               comment=None,
               existing_comment='注册时填写的category，多选，json格式',
               existing_nullable=True)
    op.alter_column('biz_customer', 'invitation_code',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=10),
               comment=None,
               existing_comment='注册时邀请码',
               existing_nullable=True)
    op.alter_column('biz_customer', 'total_score',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='剩余总积分',
               existing_nullable=True)
    op.alter_column('biz_customer', 'first_name',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100),
               comment=None,
               existing_comment='注册时填写的first_name',
               existing_nullable=True)
    op.alter_column('biz_customer', 'last_name',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100),
               comment=None,
               existing_comment='注册时填写的last_name',
               existing_nullable=True)
    op.alter_column('biz_customer', 'create_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('biz_customer', 'create_by',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40),
               comment=None,
               existing_comment='创建人id',
               existing_nullable=True)
    op.alter_column('biz_customer', 'update_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('biz_customer', 'update_by',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40),
               comment=None,
               existing_comment='更新人id',
               existing_nullable=True)
    op.alter_column('biz_customer', 'clerk_user_id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               comment=None,
               existing_comment='导购用户ID',
               existing_nullable=True)
    op.drop_table_comment(
        'biz_customer',
        existing_comment='客户表',
        schema=None
    )
    op.drop_column('biz_customer', 'my_invitation_code')
    op.alter_column('biz_score_detail', 'id',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40),
               comment=None,
               existing_comment='id',
               existing_nullable=False)
    op.alter_column('biz_score_detail', 'customer_id',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40),
               comment=None,
               existing_comment='客户id',
               existing_nullable=True)
    op.alter_column('biz_score_detail', 'score',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='变动的积分',
               existing_nullable=True)
    op.alter_column('biz_score_detail', 'before_score',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='变动前的积分',
               existing_nullable=True)
    op.alter_column('biz_score_detail', 'after_score',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='变动后的积分',
               existing_nullable=True)
    op.alter_column('biz_score_detail', 'type',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=4),
               comment=None,
               existing_comment='类型，0-注册，1-月卡，2-年卡,增值包3档对应3a、3b、3c，4-文生图扣分，5-图片融合扣分，6-款式创新扣分',
               existing_nullable=True)
    op.alter_column('biz_score_detail', 'memo',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100),
               comment=None,
               existing_comment='备注',
               existing_nullable=True)
    op.alter_column('biz_score_detail', 'biz_id',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40),
               comment=None,
               existing_comment='业务id，对应图片生成的记录id、支付流水id等。',
               existing_nullable=True)
    op.alter_column('biz_score_detail', 'order_id',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40),
               comment=None,
               existing_comment='订单id，购买商品支付成功后才有值',
               existing_nullable=True)
    op.alter_column('biz_score_detail', 'create_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('biz_score_detail', 'create_by',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40),
               comment=None,
               existing_comment='创建人id',
               existing_nullable=True)
    op.alter_column('biz_score_detail', 'update_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('biz_score_detail', 'update_by',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40),
               comment=None,
               existing_comment='更新人id',
               existing_nullable=True)
    op.drop_table_comment(
        'biz_score_detail',
        existing_comment='积分明细表',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'biz_score_detail',
        '积分明细表',
        existing_comment=None,
        schema=None
    )
    op.alter_column('biz_score_detail', 'update_by',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40),
               comment='更新人id',
               existing_nullable=True)
    op.alter_column('biz_score_detail', 'update_time',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
    op.alter_column('biz_score_detail', 'create_by',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40),
               comment='创建人id',
               existing_nullable=True)
    op.alter_column('biz_score_detail', 'create_time',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
    op.alter_column('biz_score_detail', 'order_id',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40),
               comment='订单id，购买商品支付成功后才有值',
               existing_nullable=True)
    op.alter_column('biz_score_detail', 'biz_id',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40),
               comment='业务id，对应图片生成的记录id、支付流水id等。',
               existing_nullable=True)
    op.alter_column('biz_score_detail', 'memo',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100),
               comment='备注',
               existing_nullable=True)
    op.alter_column('biz_score_detail', 'type',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=4),
               comment='类型，0-注册，1-月卡，2-年卡,增值包3档对应3a、3b、3c，4-文生图扣分，5-图片融合扣分，6-款式创新扣分',
               existing_nullable=True)
    op.alter_column('biz_score_detail', 'after_score',
               existing_type=mysql.INTEGER(),
               comment='变动后的积分',
               existing_nullable=True)
    op.alter_column('biz_score_detail', 'before_score',
               existing_type=mysql.INTEGER(),
               comment='变动前的积分',
               existing_nullable=True)
    op.alter_column('biz_score_detail', 'score',
               existing_type=mysql.INTEGER(),
               comment='变动的积分',
               existing_nullable=True)
    op.alter_column('biz_score_detail', 'customer_id',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40),
               comment='客户id',
               existing_nullable=True)
    op.alter_column('biz_score_detail', 'id',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40),
               comment='id',
               existing_nullable=False)
    op.add_column('biz_customer', sa.Column('my_invitation_code', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=10), nullable=True, comment='当前客户自己的邀请码'))
    op.create_table_comment(
        'biz_customer',
        '客户表',
        existing_comment=None,
        schema=None
    )
    op.alter_column('biz_customer', 'clerk_user_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               comment='导购用户ID',
               existing_nullable=True)
    op.alter_column('biz_customer', 'update_by',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40),
               comment='更新人id',
               existing_nullable=True)
    op.alter_column('biz_customer', 'update_time',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
    op.alter_column('biz_customer', 'create_by',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40),
               comment='创建人id',
               existing_nullable=True)
    op.alter_column('biz_customer', 'create_time',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
    op.alter_column('biz_customer', 'last_name',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100),
               comment='注册时填写的last_name',
               existing_nullable=True)
    op.alter_column('biz_customer', 'first_name',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100),
               comment='注册时填写的first_name',
               existing_nullable=True)
    op.alter_column('biz_customer', 'total_score',
               existing_type=mysql.INTEGER(),
               comment='剩余总积分',
               existing_nullable=True)
    op.alter_column('biz_customer', 'invitation_code',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=10),
               comment='注册时邀请码',
               existing_nullable=True)
    op.alter_column('biz_customer', 'category',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               comment='注册时填写的category，多选，json格式',
               existing_nullable=True)
    op.alter_column('biz_customer', 'role',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100),
               comment='注册时填写的factory',
               existing_nullable=True)
    op.alter_column('biz_customer', 'register_type',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=10),
               comment='0-账号密码登录，1-gmail登录',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('biz_customer', 'email',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100),
               comment='email',
               existing_nullable=True)
    op.alter_column('biz_customer', 'id',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=32),
               comment='主键id',
               existing_nullable=False)
    op.drop_column('biz_customer', 'my_invitation_co')
    op.create_table('ai_clothes_example',
    sa.Column('id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=40), nullable=False, comment='id'),
    sa.Column('sort', mysql.INTEGER(), autoincrement=False, nullable=True, comment='排序'),
    sa.Column('pic_url', mysql.JSON(), nullable=True, comment='图片地址'),
    sa.Column('type', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=4), nullable=True, comment='图片类型，0-裤子，1-全身，2-连体衣,3-上衣'),
    sa.PrimaryKeyConstraint('id'),
    comment='ai试衣示例图片',
    mysql_collate='utf8mb4_general_ci',
    mysql_comment='ai试衣示例图片',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('ai_clothes_model_set',
    sa.Column('id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=40), nullable=False, comment='id'),
    sa.Column('sex_value', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=40), nullable=True, comment='分类选项1'),
    sa.Column('sex_label', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=40), nullable=True, comment='分类选项1名称'),
    sa.Column('poses_value', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=40), nullable=True, comment='分类选项2'),
    sa.Column('poses_label', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=40), nullable=True, comment='分类选项2名称'),
    sa.PrimaryKeyConstraint('id'),
    comment='ai试衣的模特图集',
    mysql_collate='utf8mb4_general_ci',
    mysql_comment='ai试衣的模特图集',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('file_part_detail',
    sa.Column('id', mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=32), nullable=False, comment='分片id'),
    sa.Column('platform', mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=32), nullable=True, comment='存储平台'),
    sa.Column('upload_id', mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=128), nullable=True, comment='上传ID，仅在手动分片上传时使用'),
    sa.Column('e_tag', mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=255), nullable=True, comment='分片 ETag'),
    sa.Column('part_number', mysql.INTEGER(), autoincrement=False, nullable=True, comment='分片号。每一个上传的分片都有一个分片号，一般情况下取值范围是1~10000'),
    sa.Column('part_size', mysql.BIGINT(), autoincrement=False, nullable=True, comment='文件大小，单位字节'),
    sa.Column('hash_info', mysql.TEXT(charset='utf8mb3', collation='utf8mb3_general_ci'), nullable=True, comment='哈希信息'),
    sa.Column('create_time', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='文件分片信息表，仅在手动分片上传时使用',
    mysql_comment='文件分片信息表，仅在手动分片上传时使用',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('ai_clothes',
    sa.Column('id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40), nullable=True, comment='id'),
    sa.Column('project_id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40), nullable=True, comment='项目id'),
    sa.Column('customer_id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40), nullable=True, comment='客户id'),
    sa.Column('clothes_img1', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=200), nullable=True, comment='上传的衣服图片'),
    sa.Column('clothes_img2', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=200), nullable=True, comment='上传的裤子图片'),
    sa.Column('clothes_type', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=4), server_default=sa.text("'0'"), nullable=True, comment='衣服类型，0-上衣，1-裤子，2-全身'),
    sa.Column('aspect_ratio', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=20), nullable=True, comment='图片长宽比'),
    sa.Column('create_time', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('create_by', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40), nullable=True, comment='创建人id'),
    sa.Column('update_time', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('update_by', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40), nullable=True, comment='更新人id'),
    sa.Column('del_flag', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='逻辑删除，0-未删除，1-已删除'),
    sa.Column('model_id_json', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'), nullable=True, comment='选择的模特图的id，json格式'),
    sa.Column('model_id_in_set_json', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'), nullable=True, comment='模特图集中的模特图id，json格式'),
    sa.Column('model_img_url', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'), nullable=True, comment='最后一次生成时，使用的模特图，json格式，包括用户自己上传的。'),
    comment='i试衣操作过程中生成的结果',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='i试衣操作过程中生成的结果',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('hot_amazon',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False, comment='id'),
    sa.Column('country', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100), nullable=False, comment='国家'),
    sa.Column('country_code', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=10), nullable=True, comment='国家编码'),
    sa.Column('ranking_name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50), nullable=False, comment='销量榜'),
    sa.Column('cate_id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50), nullable=False, comment='叶子类目'),
    sa.Column('cate_lvl1_name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100), nullable=True, comment='一级类目名称'),
    sa.Column('cate_lvl2_name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100), nullable=True, comment='二级类目名称'),
    sa.Column('cate_lvl3_name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100), nullable=True, comment='三级类目名称'),
    sa.Column('ranking', mysql.BIGINT(), autoincrement=False, nullable=True, comment='类目内商品销量排名'),
    sa.Column('opp_title_ori', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True, comment='商机title（spu_title）'),
    sa.Column('opp_currency', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=10), nullable=True, comment='USD'),
    sa.Column('opp_price', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50), nullable=True, comment='商机价格selling_price_int'),
    sa.Column('asin_link', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True, comment='商品链接'),
    sa.Column('pic_link', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True, comment='商品图片'),
    sa.Column('spu_id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50), nullable=False, comment='spu_id'),
    sa.Column('sku_id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50), nullable=False, comment='sku_id'),
    sa.Column('sales_lst_30d', mysql.BIGINT(), autoincrement=False, nullable=True, comment='近30天销量'),
    sa.Column('ships_type', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=10), nullable=True, comment='配送方式：FBA|FBM'),
    sa.Column('item_weight', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50), nullable=True, comment='重量'),
    sa.Column('sold_amt_30d', mysql.DECIMAL(precision=38, scale=4), nullable=True, comment='近30天销售额'),
    sa.Column('reviews_ratings', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50), nullable=True, comment='评分人数'),
    sa.Column('reviews_stars', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50), nullable=True, comment='评分'),
    sa.Column('date_first_available', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50), nullable=True, comment='上架时间'),
    sa.Column('mth_sales_trend', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'), nullable=True, comment='月销量趋势（近半年）'),
    sa.Column('seller_id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50), nullable=True, comment='卖家id'),
    sa.Column('seller_name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100), nullable=True, comment='卖家名称'),
    sa.Column('brand_name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100), nullable=True, comment='品牌名称'),
    sa.Column('package_dimensions', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True, comment='尺寸详情'),
    sa.Column('details_ext', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'), nullable=True, comment='商品CPV数据'),
    sa.Column('ds', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True, comment='时间分区'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id', 'country', 'ranking_name', 'cate_id', 'sku_id'),
    comment='亚马逊热卖商品',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='亚马逊热卖商品',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_index('index1', 'hot_amazon', ['ds'], unique=False)
    op.create_table('ai_bag_project',
    sa.Column('id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40), nullable=True, comment='id'),
    sa.Column('customer_id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40), nullable=True, comment='客户id'),
    sa.Column('name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100), nullable=True, comment='名称'),
    sa.Column('source_img_url', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=200), nullable=True, comment='生成图片时上传的图片'),
    sa.Column('type', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100), nullable=True, comment='最后一次客户选择的包类型，生成图片时选择的type'),
    sa.Column('material', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100), nullable=True, comment='最后一次客户选择的材质，生成图片时输入的material'),
    sa.Column('color', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100), nullable=True, comment='最后一次客户选择的颜色，生成图片时输入的color'),
    sa.Column('style', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100), nullable=True, comment='最后一次客户选择的风格，生成图片时输入的style'),
    sa.Column('detail', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100), nullable=True, comment='最后一次客户选择的细节，生成图片时输入的detail'),
    sa.Column('creativity', mysql.DOUBLE(precision=6, scale=2, asdecimal=True), nullable=True, comment='最后一次客户选择的相似度，0~1间的值，生成图片时输入的creativity'),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=True, comment='最后一次客户选择的数量，1~4，生成图片时输入的quantity'),
    sa.Column('lib_id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40), nullable=True, comment='源图片库id（从库中选择时才有值），此字段预留，可能无用'),
    sa.Column('biz_type', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=2), server_default=sa.text("'0'"), nullable=True, comment='最后一次客户选择的业务类型，0-文生图（其实是图生图）,1-款式融合，2-款式创新'),
    sa.Column('other_image_url', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=200), nullable=True, comment='款式融合、创新时选择的另一张图'),
    sa.Column('create_time', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('create_by', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40), nullable=True, comment='创建人id'),
    sa.Column('update_time', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('update_by', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40), nullable=True, comment='更新人id'),
    sa.Column('material_type', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100), nullable=True, comment='包材质类型描述'),
    sa.Column('del_flag', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='逻辑删除，0-未删除，1-已删除'),
    comment='客户在工作台的项目',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='客户在工作台的项目',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('biz_customer_order',
    sa.Column('id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40), nullable=False, comment='id'),
    sa.Column('customer_id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40), nullable=True, comment='客户id'),
    sa.Column('goods_name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50), nullable=True, comment='商品名称'),
    sa.Column('goods_type', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=4), nullable=True, comment='商品类型，0-月卡，1-年卡，2-增值包1,3-增值包2,4-增值包3'),
    sa.Column('money', mysql.DOUBLE(precision=10, scale=3, asdecimal=True), nullable=True, comment='商品金额'),
    sa.Column('currency', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=20), nullable=True, comment='商品币种'),
    sa.Column('pay_time', mysql.DATETIME(), nullable=True, comment='支付时间'),
    sa.Column('valid_begin', sa.DATE(), nullable=True, comment='有效期开始时间，yyyy-MM-dd格式'),
    sa.Column('valid_end', sa.DATE(), nullable=True, comment='有效期结束时间，yyyy-MM-dd格式'),
    sa.Column('score', mysql.INTEGER(), autoincrement=False, nullable=True, comment='获得的积分'),
    sa.Column('pay_type', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=4), nullable=True, comment='支付方式，0-支付宝，1-stripe，2-微信'),
    sa.Column('pay_id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40), nullable=True, comment='对应的支付记录id，或stripe的eventId'),
    sa.Column('state', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=4), server_default=sa.text("'0'"), nullable=True, comment='订单状态，0-待支付，1-已支付，2-已取消'),
    sa.Column('del_flag', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='0-未删除，1-已删除'),
    sa.Column('create_time', sa.DATE(), nullable=True),
    sa.Column('update_time', sa.DATE(), nullable=True),
    sa.Column('create_by', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40), nullable=True),
    sa.Column('update_by', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='客户购买的套餐或增值包等商品订单',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='客户购买的套餐或增值包等商品订单',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('ai_bag_type',
    sa.Column('id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40), nullable=False, comment='id'),
    sa.Column('parent_id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40), nullable=True),
    sa.Column('code', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40), nullable=True),
    sa.Column('name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100), nullable=True),
    sa.Column('name_en', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='包图生图时可选的包类型',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='包图生图时可选的包类型',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('ai_bag_detail',
    sa.Column('id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40), nullable=False),
    sa.Column('bag_id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40), nullable=True),
    sa.Column('pic_url', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=200), nullable=True, comment='图片url，转存到自己系统oss后的地址'),
    sa.Column('create_time', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('create_by', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40), nullable=True, comment='创建人id'),
    sa.Column('update_time', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('update_by', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40), nullable=True, comment='更新人id'),
    sa.Column('source_url', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=400), nullable=True, comment='ai接口方生成的图片地址'),
    sa.Column('project_id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40), nullable=True, comment='项目id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('biz_invite_score',
    sa.Column('id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=32), nullable=False, comment='id'),
    sa.Column('code', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=20), nullable=True, comment='邀请码'),
    sa.Column('score', mysql.INTEGER(), autoincrement=False, nullable=True, comment='对应的积分'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='邀请码和对应积分',
    mysql_collate='utf8mb4_general_ci',
    mysql_comment='邀请码和对应积分',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('ai_clothes_detail',
    sa.Column('id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40), nullable=False),
    sa.Column('project_id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40), nullable=True, comment='项目id'),
    sa.Column('clothes_id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40), nullable=True, comment='结果id'),
    sa.Column('customer_id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40), nullable=True, comment='客户id'),
    sa.Column('pic_url', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=200), nullable=True, comment='AI试衣生成的图片url，转存到自己系统oss后的地址'),
    sa.Column('create_time', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('create_by', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40), nullable=True, comment='创建人id'),
    sa.Column('update_time', sa.DATE(), nullable=True, comment='创建时间'),
    sa.Column('update_by', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40), nullable=True, comment='更新人id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('ai_clothes_model',
    sa.Column('id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=40), nullable=False, comment='id'),
    sa.Column('sex_value', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=4), nullable=True, comment='性别，1-男，2-女'),
    sa.Column('sex_label', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=40), nullable=True, comment='性别的文本描述'),
    sa.Column('poses_value', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=4), nullable=True, comment='姿势选项id，1-半身，2-全身'),
    sa.Column('poses_label', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=40), nullable=True, comment='姿势的文本描述'),
    sa.Column('set_id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=40), nullable=True, comment='图集id，空说明不归属于任何图集'),
    sa.Column('pic_url', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=200), nullable=True, comment='图片地址'),
    sa.PrimaryKeyConstraint('id'),
    comment='ai试衣的模特图',
    mysql_collate='utf8mb4_general_ci',
    mysql_comment='ai试衣的模特图',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('file_detail',
    sa.Column('id', mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=32), nullable=False, comment='文件id'),
    sa.Column('url', mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=512), nullable=False, comment='文件访问地址'),
    sa.Column('size', mysql.BIGINT(), autoincrement=False, nullable=True, comment='文件大小，单位字节'),
    sa.Column('filename', mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=256), nullable=True, comment='文件名称'),
    sa.Column('original_filename', mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=256), nullable=True, comment='原始文件名'),
    sa.Column('base_path', mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=256), nullable=True, comment='基础存储路径'),
    sa.Column('path', mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=256), nullable=True, comment='存储路径'),
    sa.Column('ext', mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=32), nullable=True, comment='文件扩展名'),
    sa.Column('content_type', mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=128), nullable=True, comment='MIME类型'),
    sa.Column('platform', mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=32), nullable=True, comment='存储平台'),
    sa.Column('th_url', mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=512), nullable=True, comment='缩略图访问路径'),
    sa.Column('th_filename', mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=256), nullable=True, comment='缩略图名称'),
    sa.Column('th_size', mysql.BIGINT(), autoincrement=False, nullable=True, comment='缩略图大小，单位字节'),
    sa.Column('th_content_type', mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=128), nullable=True, comment='缩略图MIME类型'),
    sa.Column('object_id', mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=32), nullable=True, comment='文件所属对象id'),
    sa.Column('object_type', mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=32), nullable=True, comment='文件所属对象类型，例如用户头像，评价图片'),
    sa.Column('metadata', mysql.TEXT(charset='utf8mb3', collation='utf8mb3_general_ci'), nullable=True, comment='文件元数据'),
    sa.Column('user_metadata', mysql.TEXT(charset='utf8mb3', collation='utf8mb3_general_ci'), nullable=True, comment='文件用户元数据'),
    sa.Column('th_metadata', mysql.TEXT(charset='utf8mb3', collation='utf8mb3_general_ci'), nullable=True, comment='缩略图元数据'),
    sa.Column('th_user_metadata', mysql.TEXT(charset='utf8mb3', collation='utf8mb3_general_ci'), nullable=True, comment='缩略图用户元数据'),
    sa.Column('attr', mysql.TEXT(charset='utf8mb3', collation='utf8mb3_general_ci'), nullable=True, comment='附加属性'),
    sa.Column('file_acl', mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=32), nullable=True, comment='文件ACL'),
    sa.Column('th_file_acl', mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=32), nullable=True, comment='缩略图文件ACL'),
    sa.Column('hash_info', mysql.TEXT(charset='utf8mb3', collation='utf8mb3_general_ci'), nullable=True, comment='哈希信息'),
    sa.Column('upload_id', mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=128), nullable=True, comment='上传ID，仅在手动分片上传时使用'),
    sa.Column('upload_status', mysql.INTEGER(), autoincrement=False, nullable=True, comment='上传状态，仅在手动分片上传时使用，1：初始化完成，2：上传完成'),
    sa.Column('create_time', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='文件记录表',
    mysql_comment='文件记录表',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('biz_customer_category',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('value', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('value_en', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='类目表',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='类目表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('hot_cate',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False, comment='id'),
    sa.Column('type', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=2), server_default=sa.text("'0'"), nullable=True, comment='0-包分类'),
    sa.Column('cate3', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100), nullable=True, comment='三级分类名'),
    sa.Column('source_platform', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=2), nullable=True, comment='数据来源的平台，0-tk，1-亚马逊'),
    sa.Column('icon', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=200), nullable=True, comment='图标地址'),
    sa.PrimaryKeyConstraint('id'),
    comment='热卖分类表',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='热卖分类表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('hot_tk',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False, comment='id'),
    sa.Column('product_id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=False, comment='商品ID'),
    sa.Column('title', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True, comment='商品名称'),
    sa.Column('product_url', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True, comment='商品链接'),
    sa.Column('imgs_url', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=3000), nullable=True, comment='商品图片'),
    sa.Column('region', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=False, comment='国家/地区'),
    sa.Column('country_code', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=10), nullable=True, comment='国家代码'),
    sa.Column('review_cnt', mysql.BIGINT(), autoincrement=False, nullable=True, comment='评论数'),
    sa.Column('sold_cnt', mysql.BIGINT(), autoincrement=False, nullable=True, comment='总销量'),
    sa.Column('sale_amount', mysql.DECIMAL(precision=38, scale=4), nullable=True, comment='总销售额'),
    sa.Column('relate_author_cnt', mysql.BIGINT(), autoincrement=False, nullable=True, comment='关联达人数'),
    sa.Column('relate_video_cnt', mysql.BIGINT(), autoincrement=False, nullable=True, comment='关联视频数'),
    sa.Column('category_name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True, comment='类目'),
    sa.Column('product_rating', mysql.DECIMAL(precision=10, scale=4), nullable=True, comment='商品评分'),
    sa.Column('launch_time', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True, comment='上架时间'),
    sa.Column('sales_lst_30d', mysql.BIGINT(), autoincrement=False, nullable=True, comment='近30天销量'),
    sa.Column('cat_id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True, comment='类目id'),
    sa.Column('cat_name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True, comment='类目名称'),
    sa.Column('cat_level', mysql.BIGINT(), autoincrement=False, nullable=True, comment='类目层级'),
    sa.Column('sales_lst_7d', mysql.BIGINT(), autoincrement=False, nullable=True, comment='近7日销量'),
    sa.Column('sale_amount_lst_7d', mysql.DECIMAL(precision=38, scale=4), nullable=True, comment='近7日销售额'),
    sa.Column('sale_amount_lst_30d', mysql.DECIMAL(precision=38, scale=4), nullable=True, comment='近30日销售额'),
    sa.Column('sales_lst_7d_cir', mysql.DECIMAL(precision=10, scale=4), nullable=True, comment='近7日销量环比'),
    sa.Column('sales_lst_30d_cir', mysql.DECIMAL(precision=10, scale=4), nullable=True, comment='近30日销量环比'),
    sa.Column('is_cross_border', mysql.BIGINT(), autoincrement=False, nullable=True, comment='是否跨境:0否；1是'),
    sa.Column('price', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='sku最高售价'),
    sa.Column('ori_price', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='sku最高划线价'),
    sa.Column('price_min', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='sku最低售价'),
    sa.Column('ori_price_min', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='sku最低划线价'),
    sa.Column('sales_yesterday', mysql.BIGINT(), autoincrement=False, nullable=True, comment='商品昨日销量'),
    sa.Column('rank_type', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=False, comment='榜单类型，如热销榜、飙升榜、新品榜'),
    sa.Column('mth_sales_trend', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'), nullable=True, comment='月销量趋势（近半年）'),
    sa.Column('cat2_id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True, comment='二级类目id'),
    sa.Column('cat2_name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True, comment='二级类目名称'),
    sa.Column('currency', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True, comment='货币种类'),
    sa.Column('seller_id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True, comment='卖家id'),
    sa.Column('seller_name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True, comment='卖家名称'),
    sa.Column('shipping_fees', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=300), nullable=True, comment='运费'),
    sa.Column('details', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'), nullable=True, comment='商品CPV数据'),
    sa.Column('ds', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True, comment='时间分区'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id', 'product_id', 'region', 'rank_type'),
    comment='tiktok热卖',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='tiktok热卖',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_index('index1', 'hot_tk', ['ds'], unique=False)
    op.create_table('deleted_public_ids_log',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False, comment='自增主键'),
    sa.Column('deleted_public_id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50), nullable=False, comment='被删除的重复记录public_id'),
    sa.PrimaryKeyConstraint('id'),
    comment='被删除的重复记录ID日志表',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='被删除的重复记录ID日志表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_index('uk_deleted_public_id', 'deleted_public_ids_log', ['deleted_public_id'], unique=True)
    op.create_table('hot_pikpop',
    sa.Column('id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40), nullable=False, comment='id'),
    sa.Column('source_platform', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=2), nullable=True, comment='数据来源的平台，0-tk，1-亚马逊'),
    sa.Column('source_id', mysql.BIGINT(), autoincrement=False, nullable=True, comment='数据来源id，对应hot_tk等表的id'),
    sa.Column('img_urls', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=3000), nullable=True, comment='图片地址，阿里云oss地址'),
    sa.Column('country', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=300), nullable=True, comment='国家'),
    sa.Column('country_code', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=300), nullable=True, comment='国家代码'),
    sa.Column('cate1', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=300), nullable=True, comment='一级分类'),
    sa.Column('cate2', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=300), nullable=True, comment='二级分类'),
    sa.Column('cate3', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=300), nullable=True, comment='三级分类'),
    sa.Column('create_time', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('color', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=300), nullable=True, comment='提示词：颜色'),
    sa.Column('form', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=300), nullable=True, comment='提示词：风格'),
    sa.Column('material', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=300), nullable=True, comment='提示词：材质'),
    sa.Column('other', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=300), nullable=True, comment='提示词：其它、明细等'),
    sa.Column('title', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=300), nullable=True),
    sa.Column('sales_lst30d', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ds', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True, comment='时间分区'),
    sa.PrimaryKeyConstraint('id'),
    comment='本项目的热卖数据，从tk、亚马逊的表中通过过来的。',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='本项目的热卖数据，从tk、亚马逊的表中通过过来的。',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_index('index1', 'hot_pikpop', ['ds'], unique=False)
    op.create_table('ai_bag',
    sa.Column('id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40), nullable=True, comment='id'),
    sa.Column('customer_id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40), nullable=True, comment='客户id'),
    sa.Column('source_img_url', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=200), nullable=True, comment='生成图片时上传的图片'),
    sa.Column('type', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100), nullable=True, comment='生成图片时选择的type'),
    sa.Column('material', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100), nullable=True, comment='生成图片时输入的material'),
    sa.Column('color', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100), nullable=True, comment='生成图片时输入的color'),
    sa.Column('style', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100), nullable=True, comment='生成图片时输入的style'),
    sa.Column('detail', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100), nullable=True, comment='生成图片时输入的detail'),
    sa.Column('creativity', mysql.DOUBLE(precision=6, scale=2, asdecimal=True), nullable=True, comment='生成图片时输入的creativity'),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=True, comment='数量，1~4，生成图片时输入的quantity'),
    sa.Column('lib_id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40), nullable=True, comment='源图片库id（从库中选择时才有值），此字段预留，可能无用'),
    sa.Column('biz_type', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=2), server_default=sa.text("'0'"), nullable=True, comment='客户选择的业务类型，0-文生图（其实是图生图）,1-款式融合，2-款式创新'),
    sa.Column('other_image_url', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=200), nullable=True, comment='款式融合、创新时选择的另一张图'),
    sa.Column('create_time', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('create_by', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40), nullable=True, comment='创建人id'),
    sa.Column('update_time', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('update_by', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40), nullable=True, comment='更新人id'),
    sa.Column('material_type', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100), nullable=True, comment='包材质类型描述'),
    sa.Column('record_public_id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40), nullable=True, comment='接口方返回的每组图片的id，是获取图片的凭证'),
    sa.Column('img_state', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=2), nullable=True, comment='图片状态，0-生成中，1-已完成。2-生成失败'),
    sa.Column('project_id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40), nullable=True, comment='项目id'),
    comment='ai生成的包',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='ai生成的包',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('ai_clothes_project',
    sa.Column('id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40), nullable=False, comment='id'),
    sa.Column('name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100), nullable=True, comment='项目名称'),
    sa.Column('customer_id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40), nullable=True, comment='客户id'),
    sa.Column('clothes_img1', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=200), nullable=True, comment='最后一次生成图片时上传的衣服图片'),
    sa.Column('clothes_img2', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=200), nullable=True, comment='最后一次生成图片时上传的裤子图片'),
    sa.Column('clothes_type', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=4), server_default=sa.text("'0'"), nullable=True, comment='衣服类型，0-上衣，1-裤子，2-全身'),
    sa.Column('aspect_ratio', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=20), nullable=True, comment='图片长宽比'),
    sa.Column('create_time', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('create_by', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40), nullable=True, comment='创建人id'),
    sa.Column('update_time', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('update_by', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40), nullable=True, comment='更新人id'),
    sa.Column('del_flag', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='逻辑删除，0-未删除，1-已删除'),
    sa.Column('model_id_json', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'), nullable=True, comment='选择的模特图的id，json格式'),
    sa.Column('model_id_in_set_json', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'), nullable=True, comment='模特图集中的模特图id，json格式'),
    sa.Column('model_img_url', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'), nullable=True, comment='最后一次生成时，使用的模特图，json格式，包括用户自己上传的。'),
    sa.PrimaryKeyConstraint('id'),
    comment='客户在工作台的ai试衣项目',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='客户在工作台的ai试衣项目',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.drop_table('tryon_result')
    op.drop_table('tryon_project')
    op.drop_table('tryon_example')
    op.drop_table('model_library')
    # ### end Alembic commands ###
